[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "miyoo-tools"
version = "0.0.1"
dependencies = [
    "typer"
    
]

[project.scripts]
miyoo = "miyoo_tools.cli.cli:test"